@base_url = http://localhost:3000/api/questions
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVhY2hlci5jb20iLCJyb2xlIjoidGVhY2hlciIsImlhdCI6MTU5Njc0MjkwNSwiZXhwIjoxNTk2NzQ2NTA1fQ.11u6r0rN3MAwqWTAkH1Bgz0G8XdbVYamOwNeoW3ewqs

GET {{base_url}}/5f28c5661e7440196af9af5a HTTP/1.1
token: {{token}}
###

GET {{base_url}}/lessons/5f28c5661e7440196af9af5a HTTP/1.1
token: {{token}}
###

POST {{base_url}}/5f28c5661e7440196af9af5a HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "question": "Of which color is Santiago's white horse?",
  "answer": "a",
  "option_a": "White",
  "option_b": "Blue",
  "option_c": "Green",
  "option_d": "Red"
}
###
