@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAc3R1ZGVudC5jb20iLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTU5NjE0MjMwOCwiZXhwIjoxNTk2MTQ1OTA4fQ.LAQXEewQoXmwq68N50RzupQ326EQ3oFekOLfELJRZ-w
// USER ROUTES

// Teacher login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@teacher.com",
    "password": "123456"
}
###

// Student login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@student.com",
    "password": "123456"
}
###

// Create student
POST {{base_url}}/users/student HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "name": "Teacher Auth",
    "email": "auth@student.com",
    "password": "123456"
}
###

// Get all students
GET {{base_url}}/users/students HTTP/1.1
token: {{token}}
###

// Delete student
DELETE {{base_url}}/users/student/5f22ac7f23474e1c285ca54b
token: {{token}}

