@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVhY2hlci5jb20iLCJyb2xlIjoidGVhY2hlciIsImlhdCI6MTU5Njc0MjkwNSwiZXhwIjoxNTk2NzQ2NTA1fQ.11u6r0rN3MAwqWTAkH1Bgz0G8XdbVYamOwNeoW3ewqs
// USER ROUTES

// Teacher login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@teacher.com",
    "password": "123456"
}
###

// Student login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "lidia@vives.com",
    "password": "123456"
}
###

// Get profile
GET {{base_url}}/users/me HTTP/1.1
token: {{token}}

###
GET {{base_url}}/users/students/5f22dbe9152fbf604a2baa90
token: {{token}}
###

// Create student
POST {{base_url}}/users/student HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "name": "Student Auth 2",
    "email": "auth2@student2.com",
    "password": "123456"
}
###

// Get all students
GET {{base_url}}/users/students HTTP/1.1
token: {{token}}
###

// Delete student
DELETE {{base_url}}/users/student/5f22ac7f23474e1c285ca54b
token: {{token}}
###

// Complete lesson
PUT {{base_url}}/users/student/lesson/5f28c5661e7440196af9af5a
token: {{token}}